import re
from datetime import datetime
from zoneinfo import ZoneInfo

def _clean_text(text):
    '''Replaces pipes to prevent breaking markdown tables.'''

    if not text:
        return ''
    return re.sub(r'\s+', ' ', text.replace('|', ' - ').strip())

def _generate_table_rows(columns):
    '''Iterates through columns to build table rows.'''

    rows = []
    if not columns:
        return "| *No columns found* | - | - |"

    for c, column in enumerate(columns):
        col_name = column.get('name', f'Column_{c}')
        col_type = column.get('type', 'string')
        col_desc = column.get('description', '')

        row = f"| **{col_name}** | `{col_type}` | {col_desc} |"
        rows.append(row)

    return '\n'.join(rows)

def dataset_to_markdown(dataset_metadata):
    '''Turns dictionary of dataset metadata into markdown string.'''

    ds_name = dataset_metadata.get('name', 'unnamed dataset')
    ds_type = dataset_metadata.get('type', 'unknown type')
    ds_conn = dataset_metadata.get('connection', 'unknown connection')
    ds_proj = dataset_metadata.get('project_name', 'unknown project name')
    ds_pkey = dataset_metadata.get('project_key', 'unknown project key')
    ds_summary = _clean_text(dataset_metadata.get('short_description', 'No summary available.').replace('#', ''))
    ds_description = _clean_text(dataset_metadata.get('long_description', 'No detailed description provided.').replace('#', ''))

    if not ds_summary:
        ds_summary = 'No summary available.'

    if not ds_description:
        ds_description = 'No detailed description provided.'

    columns = dataset_metadata.get('columns', [])
    table_rows = _generate_table_rows(columns)

    timestamp = datetime.now(ZoneInfo("America/New_York")).strftime('%Y-%m-%d %H:%M:%S %Z')

    markdown_output = \
f"""
# {ds_name}
**{ds_summary}**

## Overview
{ds_description}
> Source: **{ds_proj} ({ds_pkey})**\nType: **{ds_conn} ({ds_type})**

## Data Dictionary
| Column Name | Type | Description |
| :--- | :---: | :--- |
{table_rows}

---
*Auto-generated by **wiki_generator** on {timestamp}*
"""

    return markdown_output